version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.bugsnag:bugsnag-android-ndk
    versions:
    - 5.5.2
    - 5.6.0
    - 5.6.2
    - 5.7.0
    - 5.7.1
    - 5.8.0
    - 5.9.0
  - dependency-name: org.rm3l:maoni
    versions:
    - 8.3.2
    - 9.0.0
